controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
main:
    path: /main
    controller: App\Controller\MainController::index
infos_modif:
    path: /infos/modif
    controller: App\Controller\InformationsPersonnellesController::afficherInformations
eventt_add:
    path: '/calandar'
    controller: 'App\Controller\CalandarController::index'
    methods: ['POST']
event_add:
    path: '/calandar/{idAnnonce}'
    controller: 'App\Controller\CalandarController::index'

