<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU4Wy4qe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU4Wy4qe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU4Wy4qe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU4Wy4qe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU4Wy4qe\App_KernelDevDebugContainer([
    'container.build_hash' => 'U4Wy4qe',
    'container.build_id' => 'cd337c54',
    'container.build_time' => 1707134896,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU4Wy4qe');
